### ISSUE TITLE
Make profile configurable

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/cameraConfiguration#18]
Instead of hard-coding the profile, we should allow users to specify the active and neutral profiles in the configuration.
This could look somewhat like this:

```yaml
    - url: http://camera.example.com
      type: panasonic
      user: admin
      password: admin
      profile:
        active: 1
        inactive: 10
```
